project:
  type: website
  output-dir: docs

website:
  title: "Ross Wilson"
  navbar:
    title: false
    logo: images/ou-logo.png
    logo-href: https://uo-cmor.github.io
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      dark: slate
      light: flatly
    page-layout: full
    css: styles.css
    toc: false
    csl: vancouver.csl

language:
  section-title-citation: "Recommended citation:"
  appendix-attribution-cite-as: " "
