project:
  type: website
  output-dir: docs

website:
  title: "Ross Wilson"
  navbar:
    title: false
    logo: images/ou-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme: slate
    page-layout: full
    css: styles.css
    toc: false

appendix-cite-as: "display"
language:
  section-title-citation: "Recommended citation:"
  appendix-attribution-cite-as: " "
