project:
  type: website
  render:
    - "index.qmd"
    - "research.qmd"
    - "teaching.qmd"
    - "articles/**/index.qmd"
    - "teaching/on-writing-well.html"

website:
  title: "Ross Wilson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      - cosmo
      - brand
      - custom.scss
    toc: true

execute:
  echo: false
  output: asis
  warnings: false
  error: false



