---
title: "My Research"

listing:
  - id: publications
    contents: "publications/*.qmd"
    template: publications/citations.ejs
    sort: "date desc"
  - id: conferences
    contents: "conferences/*.qmd"
    template: conferences/citations.ejs
    sort: "date desc"
  - id: other-reports
    contents: "other-reports/*.qmd"
    template: other-reports/citations.ejs
    sort: "date desc"

format:
  html:
    toc: true
    toc-depth: 3
---

## Research Projects

#### Reducing the burden of osteoarthritis in Aotearoa New Zealand (2022 -- 2027)

Our research centre was awarded an HRC Programme grant to investigate optimal ways to improve the management of osteoarthritis in NZ. This research programme involves a randomised clinical trial of a novel lifestyle intervention consisting of exercise therapy, dietary change, and self-management education, for people with osteoarthritis and multimorbidity; epidemiological and health economic research on the impacts of osteoarthritis prevention and management strategies, and health economic simulation modelling to evaluate the effectiveness and cost-effectiveness of novel treatment pathways and models of care for osteoarthritis in the New Zealand healthcare system. I am leading the simulation modelling project within this research programme. For more information on this programme, please see the [CMOR website](https://uo-cmor.github.io/our-work/).

#### Measuring the health state preferences of New Zealanders (2022 -- 2026)

I was awarded a project grant from the Health Research Council of New Zealand to investigate the validity of the SF-6D health state utility instrument in the New Zealand population, to derive a NZ population value set for the SF-6D, and to develop tools to support the use of the instrument for population health and equity monitoring and cost-effectiveness evaluation of healthcare in the NZ health system. At present the SF-6D, and the SF-12 health status questionnaire from which it is derived, is widely used in clinical practice, population health monitoring, and health research in NZ, without evidence of its validity for this population or the availability of a utility value set based on preferences elicited from the NZ population. This mixed methods project will combine qualitative kaupapa Māori research methods to evaluate the appropriateness of the SF-6D for the NZ, and especially Māori, population; instrument development if required to refine the SF-6D to meet the needs of the NZ population and healthcare system; and cutting-edge discrete choice experiment (DCE) survey methods to develop a value set reflecting the preferences of the NZ population for the trade-offs between health-related quality of life domains inherent in healthcare prioritisation and funding decisions.

#### Chronic opioid use following joint replacement surgery (2018 -- ongoing)

I have received grants from the Otago Medical Research Foundation and the H.S and J.C Anderson Charitable Trust for studies of the prevalence, risk factors, and consequences of chronic opioid use before and after total hip and knee replacement surgery, using linked national population data from the IDI. We showed, using a comprehensive dataset including all joint replacement surgeries performed in the NZ public healthcare system, the continued prevalence of opioid use for as long as three years after surgery; this work has been published in the New Zealand Medical Journal and presented to the NZ Orthopaedic Association Annual Scientific Meeting. A second paper from this project identifies several important risk factors that can to help identify patients at high risk of such prolonged post-surgical opioid use, which could be useful in identifying targeted interventions to reduce opioid exposure for these at-risk groups; this paper has been published in the Journal of Arthroplasty. A further study investigating the long-term health, economic, and social impacts of perioperative opioid prescribing is now under review for publication.

#### The health economic case for implementing ACL injury prevention interventions (2020 -- ongoing)

I am part of a project, led by Dr Yana Pryymachenko, that has received preliminary funding from the Health Research Council of New Zealand to investigate the impact of ACL injury prevention programmes on long-term outcomes, including the incidence and associated health and economic burden of early knee osteoarthritis. This preliminary project involves investigating the feasibility of using matching methods to identify comparable groups of individuals with and without the occurrence of an ACL injury, using comprehensive linked national data from the IDI, and to use these matched cohorts to evaluate long-term outcomes following an ACL injury. If this feasibility study proves successful, we intend to use this approach to inform cost-effectiveness evaluations of injury prevention strategies to support the implementation and uptake of such programmes across the New Zealand population (for example, via schools, sports clubs, and workplaces where people are at risk of ACL injury).

::: {.callout-note collapse="true" appearance="minimal"}
## Previous research projects

#### The primary care management and impact of osteoarthritis (2018 -- 2021)

I was part of a team awarded a Health Research Council project grant to investigate the prevalence, management pathways, and health and economic impacts of hip and knee osteoarthritis in primary care in New Zealand. Most osteoarthritis care and management, in New Zealand and elsewhere, is delivered in primary care, but very little is known, at a systematic level, about how many patients present to primary care with osteoarthritis symptoms, what treatments they are offered, and how much it costs both the health system and patients themselves. This project combined novel large-scale data extraction from primary care patient records with the wealth of data on secondary care utilization, pharmaceutical prescriptions, and wider economic and social indicators available from the Statistics New Zealand Integrated Data Infrastructure (IDI), to address these important questions. Final research papers on the health and economics impacts of osteoarthritis diagnosed and managed in primary care in NZ are now being completed for publication.

#### Computer simulation modelling for osteoarthritis in New Zealand (2015 -- 2020)

This work was part of a project, led by Prof. Haxby Abbott at the Centre for Musculoskeletal Outcomes Research, to develop and evaluate a novel, early, coordinated programme of care for osteoarthritis in the New Zealand healthcare system. For this programme, I have led the development of a new microsimulation model of the population health impacts, healthcare costs, and treatment outcomes of osteoarthritis in New Zealand, which will be used for evaluating the cost-effectiveness of the proposed programme of care. A journal article reporting on the model development and validation was published in Osteoarthritis and Cartilage, a study applying the model to provide projections of the future burden of osteoarthritis to the NZ health system and society has been published in the New Zealand Medical Journal, and an application of the model to cost-effectiveness analysis of interventions for the management of osteoarthritis in the NZ population has recently been published in Osteoarthritis and Cartilage Open as well as being presented at several conferences (including the OARSI World Congress, ISPOR European Congress, SMDM Annual Meeting, NZ Orthopaedic Association Annual Scientific Meeting, and Australian Physiotherapy Conference).

#### Total joint replacement and non-operative management for late-stage hip and knee osteoarthritis

I have been involved in several studies using data from patients undergoing total joint replacement or non-operative management for late-stage hip and knee osteoarthritis at Dunedin Public Hospital, investigating the outcomes of each of these management pathways and the optimal selection of patients for surgery. These studies have included evaluations of the 'Joint Clinic', a multidisciplinary chronic disease management pathway designed to improve access to joint replacement surgery for patients with hip and knee osteoarthritis by providing optimal non-operative management for patients with lower need for immediate surgery, with two articles published in the Journal of Arthroplasty; evaluation of the relationship between preoperative health status and postoperative improvement to help inform rationing decisions, published in Arthroplasty Today; and cost-effectiveness analysis of total joint replacement surgery based on preoperative patient characteristics and duration of follow-up, with a manuscript forthcoming in the Journal of Arthroplasty.

#### Trends in population BMI in New Zealand (2017)

This study analysed the increasing trends seen in population BMI in New Zealand over recent decades, using an Age-Period-Cohort (APC) analysis, and provides medium-term predictions of mean BMI and obesity prevalence for the next 20 years. APC analysis is a statistical methodology, widely used in disease epidemiology as well as the social sciences, for decomposing longitudinal trends in outcomes such as disease prevalence into the contributions of life-course changes (age effects), generational replacement (cohort effects), and secular time trends (period effects). In the case of BMI trends in New Zealand, we found that almost all of the observed and predicted increase in BMI was due to secular period trends, reflecting the effects of the increasingly obesogenic environment in which we live (such as the increasing availability of low-nutrient, high-energy 'junk foods', and reduced levels of physical activity due to sedentary occupations and passive leisure activities). A journal article reporting on these findings has been published in the Australian and New Zealand Journal of Public Health.

#### The health impact of osteoarthritis: health-loss burden and cross-instrument mapping (2017 -- 2019)

This project, which was funded by a Jack Thomson Arthritis Grant from the Otago Medical Research Foundation, includes two studies looking at the evaluation of the health-related quality of life impacts associated with osteoarthritis. The first study provides estimates of the health utility losses across multiple dimensions of health associated with radiographic knee osteoarthritis. To evaluate the cost-effectiveness of disease prevention strategies for osteoarthritis requires such estimates; this was the first study worldwide to provide these for radiographic knee osteoarthritis. An article reporting on this study has been published in Rheumatology.

The second study provides a tool to map from a generic quality of life measure (the SF-12) to health utility values in populations with osteoarthritis. The SF-12 is widely used in outcomes research in osteoarthritis, but the outcome measures commonly reported do not provide the utility values needed for cost-effectiveness analysis. This mapping will therefore greatly increase the range of studies available to inform economic analyses. A journal article reporting on this study is currently being finalised.

:::

## Publications and outputs

### Journal articles

:::{#publications}
:::

### Conference presentations

:::{#conferences}
:::

### Other reports

:::{#other-reports}
:::
