Back to #link("/research.html#journal-articles")[publications]

= Reducing the burden of knee osteoarthritis through community pharmacy: protocol for a randomised controlled trial of the Knee Care for Arthritis through Pharmacy Service (KneeCAPS)
== Musculoskeletal Care
#smallcaps[Published]\ 22 May 2023

#smallcaps[Citation]\ Darlow B, Brown M, Stanley J, Abbott H, Briggs A, Clark J, Frew G, Grainger R, Hood F, Hudson B, Keenan R, Marra C, McKinlay E, Pask A, Pierobon A, Simmonds S, Vincent L, Dean S. #link("articles/10.1002/msc.1785/index.typ")[Reducing the burden of knee osteoarthritis through community pharmacy: protocol for a randomised controlled trial of the Knee Care for Arthritis through Pharmacy Service (KneeCAPS)]. _Musculoskeletal Care_ 2023;2141053–1067. doi:#link("https://doi.org/10.1002/msc.1785")[10.1002/msc.1785]

=== Abstract
**Introduction**<br>Knee osteoarthritis (OA) negatively impacts the health outcomes and equity, social and employment participation, and socio-economic wellbeing of those affected. Little community-based support is offered to people with knee OA in Aotearoa New Zealand. Identifying Māori and non-Māori with knee OA in community pharmacy and providing co-ordinated, evidence- and community-based care may be a scalable, sustainable, equitable, effective and cost-effective approach to improve health and wellbeing.<br><br>**Aim**<br>Assess whether the Knee Care for Arthritis through Pharmacy Service (KneeCAPS) intervention improves knee-related physical function and pain (co-primary outcomes). Secondary aims assess impacts on health-related quality of life, employment participation, medication use, secondary health care utilisation, and relative effectiveness for Māori.<br><br>**Methods and analysis**<br>A pragmatic randomised controlled trial will compare the KneeCAPS intervention to the Pharmaceutical Society of New Zealand Arthritis Fact Sheet and usual care (active control) at 12 months for Māori and non-Māori who have knee OA. Participants will be recruited in community pharmacies. Knee-related physical function will be measured using the function subscale of the Short Form of the Western Ontario and McMaster Universities Osteoarthritis Index. Knee-related pain will be measured using an 11-point numeric pain rating scale. Primary outcome analyses will be conducted on an intention-to-treat basis using linear mixed models. Parallel within-trial health economic analysis and process evaluation will also be conducted.<br><br>**Ethics and trial dissemination**<br>Ethical approval was obtained from the Central Health and Ethics Committee (2022-EXP-11725). The trial is registered with ANZCTR (ACTRN12622000469718). Findings will be submitted for publication and shared with participants.
