Back to #link("/research.html#journal-articles")[publications]

= Cost-effectiveness of low dose colchicine prophylaxis when starting allopurinol using the “start-low go-slow” approach for gout: evidence from a non-inferiority randomised double-blind placebo-controlled trial
== Arthritis Care & Research
#smallcaps[Published]\ 25 November 2025

#smallcaps[Citation]\ Pryymachenko Y, Wilson R, Dalbeth N, Abbott JH, Stamp L. #link("articles/10.1002/acr.25631/index.typ")[Cost-effectiveness of low dose colchicine prophylaxis when starting allopurinol using the “start-low go-slow” approach for gout: evidence from a non-inferiority randomised double-blind placebo-controlled trial]. _Arthritis Care & Research_ 2025;In press. doi:#link("https://doi.org/10.1002/acr.25631")[10.1002/acr.25631]

=== Abstract
**Objective**<br>The aim of this study was to investigate the cost-effectiveness of low-dose colchicine prophylaxis for preventing gout flares when starting allopurinol using the “start-low go-slow” approach.<br><br>**Methods**<br>Participants with gout, fulfilling the American College of Rheumatology recommendations for starting urate-lowering therapy and with serum urate ≥0.36 mmol/L (6mg/dL), were randomly allocated (1:1) to either colchicine (0.5 mg daily) or placebo for six months with a further six-month follow-up. All participants received allopurinol, with monthly increase in dose to achieve target urate <0.36 mmol/L. The primary outcomes were incremental cost-effectiveness at 6-month and 1-year follow-up from the health system perspective, measured by incremental net monetary benefit (INMB) at a willingness-to-pay threshold equivalent to gross domestic product per capita.<br><br>**Results**<br>Two hundred participants were randomized to either colchicine (n=100) or placebo (n=100). Mean costs were higher in the colchicine group over both 6 months and 1 year (adjusted mean difference $1 848 [95%CI −321 to 4 017] and $2 282 [95%CI −173 to 4 737], respectively). Quality-adjusted life years were slightly higher in the colchicine group over 6 months (adjusted mean difference 0.008 [95%CI −0.020 to 0.035]), but lower over 1 year (−0.015, [95%CI −0.039 to 0.010]). Treatment with colchicine was not found to be cost-effective at either 6-months or 12-months (INMB −$1 373 (95%CI −4 287 to 1 542) and −$3 191 (95%CI −6 274 to −107), probability of cost-effectiveness 17.7% and 1.5%, respectively). Similar results were obtained from a societal perspective.<br><br>**Conclusion**<br>Six months of low-dose colchicine prophylaxis when starting allopurinol using the “start-low go-slow” approach is unlikely to be cost-effective over 12 months.
