Back to #link("/research.html#journal-articles")[publications]

= A Guideline-Implementation Intervention to Improve the Management of Low Back Pain in Primary Care: A Difference-in-Difference-in-Differences Analysis
== Applied Health Economics and Health Policy
#smallcaps[Published]\ 6 December 2022

#smallcaps[Citation]\ Wilson R, Pryymachenko Y, Abbott JH, Dean S, Stanley J, Garrett S, Mathieson F, Dowell A, Darlow B. #link("articles/10.1007/s40258-022-00776-3/index.typ")[A Guideline-Implementation Intervention to Improve the Management of Low Back Pain in Primary Care: A Difference-in-Difference-in-Differences Analysis]. _Applied Health Economics and Health Policy_ 2023;21253–262. doi:#link("https://doi.org/10.1007/s40258-022-00776-3")[10.1007/s40258-022-00776-3]

=== Abstract
**Background**<br>Real-world adherence to clinical practice guidelines is often poor, resulting in sub-standard patient care and unnecessary healthcare costs. This study evaluates the effect of a guideline-implementation intervention for the management of low back pain (LBP) in general practice–the Fear Reduction Exercised Early (FREE) approach—on LBP-related injury insurance claims, healthcare utilisation, and costs of treatment.<br><br>**Design**<br>Data were extracted from comprehensive nationwide New Zealand injury insurance claims records. Data were analysed using a ‘triple-difference’ (difference-in-difference-in-differences) method to isolate the causal effect of FREE training on LBP claims activity, comparing the difference in general practitioner (GP) LBP claims and associated activity before and after training with their non-musculoskeletal injury claims for the same periods (assumed to be unaffected by training), relative to the same comparisons for GPs not trained in the FREE approach.<br><br>**Results**<br>Training GPs in the FREE approach resulted in significant reductions in the number of LBP injury claims lodged (− 19%, 95% CI −34 to −5), the use of physiotherapy (−30%, 95% CI − 42 to − 18) and imaging (− 27%, 95% CI − 46 to − 8%), and the healthcare costs (− 21%, 95% CI − 41 to − 1) of LBP injury. Changes in claims for earnings’ compensation (− 10%, 95% CI − 34 to 13) were not significant.<br><br>**Conclusions**<br>A brief guideline-implementation intervention following best-practice LBP management and guideline-implementation strategies achieved significant reductions, persisting over at least 6 to18 months, in healthcare utilisation consistent with improved delivery of guideline-concordant care.
