Back to #link("/research.html#journal-articles")[publications]

= Reliability, validity, responsiveness, and minimum important change of the Stair Climb Test in adults with hip and knee osteoarthritis
== Arthritis Care & Research
#smallcaps[Published]\ 24 November 2022

#smallcaps[Citation]\ Sharma S, Wilson R, Pryymachenko Y, Pathak A, Chua J, Gwynne-Jones D, Bennell KL, Metcalf B, Hinman RS, Lim B-W, Abbott JH. #link("articles/10.1002/acr.24821/index.typ")[Reliability, validity, responsiveness, and minimum important change of the Stair Climb Test in adults with hip and knee osteoarthritis]. _Arthritis Care & Research_ 2023;7551147–1157. doi:#link("https://doi.org/10.1002/acr.24821")[10.1002/acr.24821]

=== Abstract
**Objective**<br>The Osteoarthritis Research Society International (OARSI) recommends assessment of physical function using a performance-based test of stair negotiation but was unable to recommend any specific test. We assessed the reliability, validity, responsiveness, measurement error, and minimum important change (MIC) of the 6-step timed Stair Climb Test (SCT).<br><br>**Methods**<br>We used pooled data from 397 participants with hip or knee osteoarthritis (54% women) from 4 clinical trials (86% retained at 12-week follow-up). Construct validity was assessed by testing 6 a priori hypotheses against other OARSI-recommended physical function measures. A self-reported Global Rating of Change scale was used to classify participants as worsened, improved, and stable. Participants who worsened in physical function were excluded from all analyses. Responsiveness and MIC were assessed using multiple anchor-based and distribution-based approaches. Test–retest reliability, standard error of measurement (SEM), and smallest detectable change (SDC) were assessed on stable participants.<br><br>**Results**<br>Five of 6 hypotheses (83%) for construct validity were met. Test–retest reliability was excellent (intraclass correlation coefficient2,1 0.83; 95% confidence interval 0.71–0.90). The SEM and SDC values were 0.44 and 1.21 seconds, respectively. We did not find adequate support for responsiveness. The MIC values ranged from 0.78 to 1.95 seconds using different approaches (median 1.37 seconds).<br><br>**Conclusion**<br>The 6-step timed SCT adequately assesses the construct of physical function in individuals with hip or knee osteoarthritis with excellent 12-week test–retest reliability. However, support for its responsiveness was inadequate to recommend its use as an outcome measure in people with osteoarthritis for research and clinical practice.
